services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: "rabbitmq-host"
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    healthcheck:
      #test: ["CMD", "curl", "-f", "http://localhost:15672"] #["CMD", "rabbitmq-diagnostics", "ping"]
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - rabbitnetwork
  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    container_name: producer
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    environment:
      RABBITMQ_HOST: rabbitmq-host
      RABBITMQ_PORT: 5672
    restart: on-failure
    networks:
      - rabbitnetwork
  consumer:
    container_name: consumer
    build:
      context: ./consumer
      dockerfile: Dockerfile
    restart: on-failure
    depends_on:
      rabbitmq:
        condition: service_healthy
        restart: true
    environment:
      RABBITMQ_HOST: rabbitmq-host
      RABBITMQ_PORT: 5672
    networks:
      - rabbitnetwork

networks:
  rabbitnetwork:
    driver: bridge